#cp ./data/ms /home/runner/work/Advanced_Materials_Engineer/doc/data/
name: ChemName2CID

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: running ChemName2CID

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: running chemname2cid
      run: |
         git config --global user.email "ucecwme@ucl.ac.uk"
         git config --global user.name "nickcafferry"
         git init
         echo "Initializing the program....................."
         
         echo "---------------------------------------------"
         cd ../
         mkdir output
         echo "output file already created!"
         
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: running .py file
      run: |
         echo "---------------------------------------------"
         cd doc/
         export PATH="$PATH:/home/runner/.local/bin:/home/runner/Advanced_Materials_Engineer/Advanced_Materials_Engineer/doc/"
         pip3 install --upgrade pip
         pip3 install wheel
         pip3 install requests
         pip3 install pandas
         pip3 install -U scikit-learn
         python3.8 -m pip install -U pymupdf
         python3.8 IR_MS_Data_Scrap.py
         ls

         echo "recording information already unpacked!"
         echo "Show the path of this file:"
         pwd
         echo "---------------------------------------------"
         
         cd ./doc/data/mass/
         wget https://binstar-cio-packages-prod.s3.amazonaws.com/5ee2062083b66372f61747a9/6178052cc16f55df0297e8cc?response-content-disposition=attachment%3B%20filename%3D%22rdkit-2021.09.2-py39hfadf033_0.tar.bz2%22%3B%20filename%2A%3DUTF-8%27%27rdkit-2021.09.2-py39hfadf033_0.tar.bz2&response-content-type=application%2Fx-tar&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Expires=60&X-Amz-Date=20211207T095907Z&X-Amz-SignedHeaders=host&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEMn%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJHMEUCIQDWnPqi2zwBuERdb8v95pkgQpvYYQcDbxpoFaZFm6W0hQIgKRxR%2FztOpG3bpToSiIvT460YAHgPcx1Nzsdw4o0ZGnoqgwQIov%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAAGgw0NTU4NjQwOTgzNzgiDMAOvdINJKSqMZA4yCrXAwES%2FJhPgQDRHLHMhS7rnFuRQ96cxowS3n0yiMSeOsjVEKWFc56Y6m4PVPZ55ZqEQy5PW7LUmUWFpBUB6Ze7OfmGt0a8%2BjJHlBrFvfNCSpYOefQNbbg6yp9jhWmdsAnQqk3eb9DUXLCTIgOzjnSL2ETfvLr2f5JWjlVaF3Lh5N5VvhLUzFdOBuobZHHLyBK2AYFZ1thrGcDDv6ncf6oczyNv1i7l8oGtstumE0sgt0p8qA%2FLkpc%2BxS3F3W3wWLhAbZA0L4jCmmurhL1p4BevHZd5q7hOkFsCqHIR9wvA9T4yX80lBVTQpUirRNd2RWqK5%2F9P0Cizu4aub26SYfQiyW2PPE2XIGHtCMh9EzC5KSIi3OvqMhOiaav%2Bstp3erf0dHNQSbdBE88R0Fz%2FhiftY8QtE0UPiZqjrwBX4eVLgNZkvupCY60vIw9S2SkilpAcYGuPmJm0UjgW33FWDYs6MVox%2FIlEmwN0UwOPNeh6xf5tsl3Wk%2FYrLgDoqv4TkcOR%2FcrPGUjwxUMIeWOcvonMfYu8Yg6nIyTO%2FFbya6if80nr1apaf1tH1Huy4sFOYq1UmmdjUKBmbcVj%2Fc94kypkFeCwjFWmlNNn%2FSzndm7qAOV9JLP1IijhqjCCvLyNBjqlAaLx61%2BW5vvJchmHWC6%2FkNwcFJ0fGdlGH4rkgZpkdmS7YQ%2B7hCw5cqACjm7KTpeBvRx7CVGeUlMoVRRc34SHqvrtAEu9qIzcWQWT1xXhxdSrkShTGlrKYZBco0xt818j0UkW1o7I83WnBO7zQJD0EoXBirpx071aeH4JG3CiJbKiWwdJ1E2t7nVfnqv4z9tVrcaerZwx5fMBV1as0mxD2HHfqxLuKw%3D%3D&X-Amz-Credential=ASIAWUI46DZFGUKBVU5E%2F20211207%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=56a839fe0521b633e07bab8d06a271f5015ef38b741bfc8a5e3be4e9596a8ded
         
         echo "transporting new outputs to artifacts..."
         cp -r /home/runner/work/Advanced_Materials_Engineer/Advanced_Materials_Engineer/doc/data/mass /home/runner/work/Advanced_Materials_Engineer/output/

                
         cd /home/runner/work/Advanced_Materials_Engineer/Advanced_Materials_Engineer/
         git push origin master
        
         echo "checking the artifacts..."
         cd /home/runner/work/Advanced_Materials_Engineer/output/
         ls
         pwd
         
    - uses: actions/upload-artifact@v2
      with:
        name: output results
        path: /home/runner/work/Advanced_Materials_Engineer/output/
