name: ChemName2CID

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: running ChemName2CID

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: running chemname2cid
      run: |
         git config --global user.email "ucecwme@ucl.ac.uk"
         git config --global user.name "nickcafferry"
         git init
         echo "Initializing the program....................."
         
         echo "---------------------------------------------"
         cd ../
         mkdir output
         echo "output file already created!"
         
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: running .py file
      run: |
         echo "---------------------------------------------"
         cd doc/
         export PATH="$PATH:/home/runner/.local/bin:/home/runner/Advanced_Materials_Engineer/Advanced_Materials_Engineer/doc/"
         pip3 install --upgrade pip
         pip3 install wheel
         python3.8 -m pip install -U pymupdf
         python3.8 IR_MS_Data_Scrap.py
         ls

         echo "recording information already unpacked!"
         echo "Show the path of this file:"
         pwd
         echo "---------------------------------------------"
         
         echo "transporting new outputs to artifacts..."
         cp ./data/ir /home/runner/work/Advanced_Materials_Engineer/doc/data/
         cp ./data/ms /home/runner/work/Advanced_Materials_Engineer/doc/data/
                
         cd /home/runner/work/Advanced_Materials_Engineer/Advanced_Materials_Engineer/
         git push origin master
        
         echo "checking the artifacts..."
         cd /home/runner/work/Advanced_Materials_Engineer/doc/data/
         ls
         pwd
         
    - uses: actions/upload-artifact@v2
      with:
        name: output results
        path: /home/runner/work/Advanced_Materials_Engineer/doc/data/
